SELECT 
  ?person
  ?birthName
  ?personLabel
  (COALESCE(?birthName, ?personLabel) AS ?fullName) 
  ?dateOfBirth 
  ?placeOfBirthLabel 
  (IF(BOUND(?dateOfDeath), ?dateOfDeath, "alive") AS ?finalDateOfDeath) 
  (IF(BOUND(?dateOfDeath), COALESCE(?mannerOfDeathLabel, "unknown"), "alive") AS ?finalMannerOfDeath)
WHERE {
  VALUES ?person { wd:Q46780 wd:Q39562 wd:Q28033373 wd:Q150872 wd:Q45662 }
  OPTIONAL { ?person wdt:P569 ?dateOfBirth. }
  OPTIONAL { ?person wdt:P19 ?placeOfBirth. }
  OPTIONAL { ?person wdt:P1477 ?birthName. }
  OPTIONAL { ?person wdt:P570 ?dateOfDeath. }
  OPTIONAL { ?person wdt:P1196 ?mannerOfDeath. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
